version: '2'
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto:/mosquitto/config/
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - 8086:8086
  openmct:
    build: .
    container_name: telemetry-server
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
      INFLUX_HOST: influxdb
      OPENMCT_CONFIG: spark.js
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8082:8082'
    links:
      - influxdb
      - mqtt
    volumes:
      - ./dict:/var/app/dict
